database:
  host: 192.168.2.236
  port: 5432
  user: postgres
  password: sml
api:
  key: ad5fec6778d9abf94de906992f0768dd1e5c6fc6502826ce1bf3cb584abe5d30
  base_url: https://api.dev.dedepos.com/
databases:
- name: data03
