services:
  smlsynctodede-1:
    image: ghcr.io/smlsoft/smlsynctodede:latest
    volumes:
      - ./config-1.yaml:/app/config.yaml
      - ./sync_log_1.txt:/app/sync_log.txt

  smlsynctodede-2:
    image: ghcr.io/smlsoft/smlsynctodede:latest
    volumes:
      - ./config-2.yaml:/app/config.yaml
      - ./sync_log_2.txt:/app/sync_log.txt
